import React, { useEffect, useState } from 'react';
import {
  ShieldAlert,
  CheckCircle2,
  XCircle,
  Clock,
  Terminal,
  AlertTriangle,
  Play,
  RotateCcw,
  ExternalLink,
} from 'lucide-react';
import { api } from '../services/api';
import { SeverityBadge } from '../components/SeverityBadge';

export const ResponseCenter: React.FC = () => {
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [priorityFilter, setPriorityFilter] = useState('ALL');
  const [loading, setLoading] = useState(true);

  const fetchResponses = async () => {
    try {
      const res = await api.getResponses();
      setRecommendations(res || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchResponses();
  }, []);

  const handleStatusChange = async (incidentId: string, recId: string, status: string) => {
    try {
      await api.updateResponseStatus(incidentId, recId, status);
      setRecommendations((prev) =>
        prev.map((r) => (r.id === recId ? { ...r, status } : r))
      );
    } catch (err) {
      console.error(err);
    }
  };

  const filtered = recommendations.filter((r) => {
    if (statusFilter !== 'ALL' && r.status !== statusFilter) return false;
    if (priorityFilter !== 'ALL' && r.priority !== priorityFilter) return false;
    return true;
  });

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-slate-900 border border-slate-800 rounded-lg p-4 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h2 className="text-sm font-bold text-white font-mono uppercase tracking-wide flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 text-emerald-400" />
            Automated Incident Response Center & Playbook Actions
          </h2>
          <p className="text-xs text-slate-400">
            Actionable containment policies generated by AI decision engine & MITRE ATT&CK mitigations
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded px-2.5 py-1 text-xs text-slate-300 font-mono focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">Status: ALL</option>
            <option value="Pending">Pending</option>
            <option value="Approved">Approved</option>
            <option value="Completed">Completed</option>
            <option value="Rejected">Rejected</option>
          </select>

          <select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
            className="bg-slate-950 border border-slate-800 rounded px-2.5 py-1 text-xs text-slate-300 font-mono focus:outline-none focus:border-cyan-500"
          >
            <option value="ALL">Priority: ALL</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="HIGH">HIGH</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="LOW">LOW</option>
          </select>
        </div>
      </div>

      {/* Action Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-lg overflow-hidden shadow-lg">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-sans">
            <thead className="bg-slate-950 text-[11px] font-mono text-slate-400 uppercase border-b border-slate-800">
              <tr>
                <th className="py-2.5 px-3">Priority</th>
                <th className="py-2.5 px-3">Remediation Action</th>
                <th className="py-2.5 px-3">Incident Reference</th>
                <th className="py-2.5 px-3">MITRE</th>
                <th className="py-2.5 px-3">Technical Justification</th>
                <th className="py-2.5 px-3">Status</th>
                <th className="py-2.5 px-3 text-right">Analyst Decision</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 font-mono text-[11px]">
              {filtered.map((rec) => (
                <tr key={rec.id} className="hover:bg-slate-800/40">
                  <td className="py-2.5 px-3">
                    <SeverityBadge severity={rec.priority} />
                  </td>
                  <td className="py-2.5 px-3 font-semibold text-white font-sans max-w-xs">
                    {rec.action}
                  </td>
                  <td className="py-2.5 px-3 text-cyan-400">{rec.incident_id}</td>
                  <td className="py-2.5 px-3 text-slate-300">{rec.mitre_technique_id}</td>
                  <td className="py-2.5 px-3 text-slate-400 font-sans max-w-sm truncate">
                    {rec.reason}
                  </td>
                  <td className="py-2.5 px-3">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold border ${
                        rec.status === 'Approved'
                          ? 'bg-cyan-950/40 border-cyan-800 text-cyan-400'
                          : rec.status === 'Completed'
                          ? 'bg-emerald-950/40 border-emerald-800 text-emerald-400'
                          : rec.status === 'Rejected'
                          ? 'bg-rose-950/40 border-rose-800 text-rose-400'
                          : 'bg-amber-950/40 border-amber-800 text-amber-400'
                      }`}
                    >
                      {rec.status}
                    </span>
                  </td>
                  <td className="py-2.5 px-3 text-right" onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end gap-1.5">
                      {rec.status === 'Pending' && (
                        <>
                          <button
                            onClick={() =>
                              handleStatusChange(rec.incident_id, rec.id, 'Approved')
                            }
                            className="px-2 py-1 rounded bg-cyan-600 hover:bg-cyan-500 text-slate-950 text-[10px] font-bold"
                          >
                            Approve
                          </button>
                          <button
                            onClick={() =>
                              handleStatusChange(rec.incident_id, rec.id, 'Rejected')
                            }
                            className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 text-[10px]"
                          >
                            Reject
                          </button>
                        </>
                      )}
                      {rec.status === 'Approved' && (
                        <button
                          onClick={() =>
                            handleStatusChange(rec.incident_id, rec.id, 'Completed')
                          }
                          className="px-2 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-slate-950 text-[10px] font-bold"
                        >
                          Complete
                        </button>
                      )}
                      {(rec.status === 'Completed' || rec.status === 'Rejected') && (
                        <button
                          onClick={() =>
                            handleStatusChange(rec.incident_id, rec.id, 'Pending')
                          }
                          className="px-2 py-0.5 rounded border border-slate-700 text-slate-400 hover:text-slate-200 text-[10px]"
                        >
                          Reopen
                        </button>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
